### ISSUE TITLE
unittest - ImageScraper

### ISSUE THREAD

**Issue by NaveenKarippai** [NaveenKarippai/image-scraper#4]
- The `unittest.main()` method not invoked. Please check if tests run success?
- ImageDownloader import error due to system path

@nathanIL  Could you please have a look.

**Comment by nathanIL** [comment]
Hi Naveen!

depends on what you are trying to achieve, basically its not a must to invoke it explicitly, you can run the following from the project's root dir (next to ImageScraper.py, etc):
_python -m unittest discover -v tests/_

and it will run all the tests under _tests/_ dir.
